[theme]
# Fond bleu nuit moderne
backgroundColor = "#0A1A2F"

# Fond secondaire gris métal clair
secondaryBackgroundColor = "#14263F"

# Texte blanc premium
textColor = "#F0F0F0"

# Accent bleu électrique (style dashboard moderne)
primaryColor = "#1E90FF"

# Police professionnelle
font = "sans serif"
